### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kiralikbeyin** [gmag11/painlessMesh#1]
Very nice library! 

Did you try maximum range of these nodes?

Are you using nodemcu or wemos or esp01... ?

**Comment by gmag11** [comment]
Hi! I've only made short range tests, during development. But should not be much different to normal wifi topology.

It is not needed that all nodes are in range of each other. Nodes in the middle act as repeaters, so theoretically mesh can extend indefinitelly. Number of nodes is the limit. There is no fixed max number in library. As all nodes keep track of network topology (all nodeIDs and their relationship) limit is RAM available on esp8266.

For my test, I'm using 2 NodeMCU and 2 Wemos D1 mini. It should run with Esp01 but I've not tested them yet.

If you try this lib, please share your experience here.

**Comment by gmag11** [comment]
I've tested connection range. With ESP12 it is not so long, only about 20 metres in free field.

Depending on scenario a board with external antenna could be better than PCB antenna. So, node density can be lower.

**Comment by kiralikbeyin** [comment]
Maybe range will be better with ready boards like nodemcu 1.0 or sonoff devices. https://www.itead.cc/wiki/Sonoff_Smart_Home_Solution
