### ISSUE TITLE
How to check the current node is connected to the mesh ?

### ISSUE THREAD

**Issue by tinamore** [gmag11/painlessMesh#3]
Hi,
I see funcion:
```
bool isConnected(uint32_t nodeId)
```
But this function check isConnected for a another node.
How to check the current node is connected to the mesh ?

I want when the current node is connected, the LED  will light to alert current Node was connected to the Mesh

Thanks.

**Comment by gmag11** [comment]
Hi, I did not thought about that. It could be done checking number of connections with `connectionCount()`. If it is grater than 0 node is connected.

Tell me if that is ok for you.

**Comment by gmag11** [comment]
Current example flashes number of times as number of connected nodes

**Comment by tinamore** [comment]
Thank you.
