### ISSUE TITLE
AP connection

### ISSUE THREAD

**Issue by ead0601** [gmag11/painlessMesh#6]
Hi,

I used your painlessmesh example and added a websocket interface to it. I have a total of seven devices, one is AP_ONLY, and the others are STA_ONLY. The AP_ONLY is the device that is running the web socket.  As you know they all share the same SSID and PASSWORD, which is great!!. However, when I have all of the devices going, and I want to connect from my Android phone, to the AP_ONLY I am having an issue. 

If I start the AP_ONLY device first, and then connect to Android, and then start up the other devices I have no issue,

However, if I start up all of the devices, and then try to connect to the AP_ONLY, it takes many tries before connecting. I believe the other devices are trying interfering, but I am unsure how since only one device is AP_ONLY.

Any help is greatly appreciated.

Thanks,
Edward

**Comment by RudyFiero** [comment]
Have you tried this with one device set up as an AP and two as station only? 

The ESP8266 can only handle a up to four stations connected. I wonder what is happening when you have more than that number trying to access the AP.
 
https://github.com/gmag11/painlessMesh/wiki#network-layout

Every node acts as an accesspoint (AP) for other nodes to connect to and as a client to connect to one AP of another node. There is a limit of 4 station nodes per AP. This limit is fixed by ESP8266 SDK.

**Comment by ead0601** [comment]
Hi,

Thank you. I did some experiments, and I just noticed the tcp_max_con.  I liked the fact that painlessMesh  allows for a SSID, but when all the devices are in STA_AP, I often end up connecting to a device that does not have a websocket. 

I only have one device with a websocket, and the others are meant to just be part of a mesh. That single websocket device is the AP to which I connect to.

I may need to go back to the easyMesh approach so that I know which AP is the one that I want to connect to.

Thanks,
Edward

**Comment by ead0601** [comment]
My solution was to make them all web sockets. Therefore, every main.cs in the data folder needs a unit specific  ws = new WebSocket('ws://10.254.155.1:2222/');, which is kind of a pain.

Since the mesh that I connect to is unknown at connection time, they all have to be able to serve the web page, and the client side javascript that starts the websocket has to know the IP before hand, hence the embedded IP in the javascript.

I wish there was a way for a mesh node to forward the tcp packets to the single desired unit that is performing the webserver function.

Thanks,
Edward

**Comment by Dickaa88** [comment]
Have You tried to make the websocket-node STA-only and create an AP on your own? Then all the other can run in STA_AP_mode

**Comment by gmag11** [comment]
Sorry @ead0601 this library uses json messages between nodes. IP forwarding is not possible.

Even, it would also be difficult with esp8266 as it is a small microcontroller with small memory.

It you define a single node as STA only you can use its AP as you want, with different  SSID name and password. Of course, code has to be different from some nodes to this special one.
