### ISSUE TITLE
Power Management

### ISSUE THREAD

**Issue by Tensa225** [gmag11/painlessMesh#7]
Did anyone try to implement power management (or (deep)sleep) options?

Using the AT command structure and or changing the node to node update interval(s) this should be possible?

My JSON programming skills aren`t that well developed to help you out, sorry for that.

**Comment by gmag11** [comment]
This project has nothing to do with AT command. It implements a library to be used in Arduino IDE framework.

JSON is not a language by itself, but a data representation based on text. On Internet you can find many simple descriptions.

**Comment by gmag11** [comment]
This supports sleep mode for a node if it is configured as STA ONLY.

AP enabled nodes should not be driven to sleep mode.

**Comment by Tensa225** [comment]
The mesh uses the same functionality to set up STA`s and AP`s as the AT commands as it taps into the SDK for the ESP8266. Although the “actual” AT commands themselves are not used.

It`s a suggestion to use the available SDK functionality in order to access sleep mode(s) and other functionality or power savings options in the SDK.

If you can distinguish between mesh maintenance and other activity you might be able to limit mesh update intervals in between and possibly use SDK sleep modes to save power.

At this point one can`t be sure if it will be a AP or STA although average power use will be the same due to the 5/1, STA and AP distribution, within the nodes.

Where did I mention JSON to be a language? Is this your way of suggesting I should learn JSON to help you out?

**Comment by gmag11** [comment]
Sorry, I do not get what you mean. May you reformulate your question or suggestion?

**Comment by RudyFiero** [comment]
@Tensa225  Are you sure that the AT commands are still there when a new program has been loaded? From what I read so far that does not seem to be the case. Have you loaded an Arduino sketch and still been able to access the AT commands? My guess is no. The low level calls are still there I expect the command interpreter is gone.

Also it might be good to keep in mind that this is called painlessMesh and not doEverythingMesh. It is a messaging system and you still can develop your own code to do special functions that you need.

**Comment by Tensa225** [comment]
The actual AT commands themselves probably aren`t there however the same functionality within the SDK, otherwise accessed by the AT commands, should be I think?

Regardless of any programming on top of the SDK the functionality within it should remain the same. The mesh code doesn`t change the SDK included in Arduino? I didn`t try to access them in Arduino, possibly it will work and maybe I will try. I did use the AT commands, using the AT commands .bin(s) directly.

How to access the SDK functionality would probably be the question. Maybe the SDK can “swallow” the AT commands directly using Arduino code?

If people want to run a mesh “off-grid”  they possibly want to reduce power consumption. 

I didn`t measure the power consumption currently used by the mesh but probably i will at some point. 

For the application I`m working on reducing power is actually not on top of the list but could it be useful.

I understand it`s not a "doEverythingMesh" but why not make it one, possibly using an additional library? 

Can`t help you out with the JSON code.

**Comment by RudyFiero** [comment]
>I understand it`s not a "doEverythingMesh" but why not make it one, possibly using an additional library?

Sure. And you are free to contribute to the capabilities of the program. 

I think you are misunderstanding gmag11's comment because he is not asking for help on using JSON. My read of what he said is that you need to understand the JSON data handling if you want to make use of the painlessMesh communications.

**Comment by Tensa225** [comment]
Yes but my JSON is not really that great (understatement here).

Therefore I decided to suggest it here. It`s not actually an "issue" but they don`t have a separate comment section on GitHub.

Maybe some day I need to learn JSON but for now... You guys would probably do a better job.

**Comment by Tensa225** [comment]
Would like you like to know the application I use the mesh for?

**Comment by Tensa225** [comment]
Wireless Pigeons. A white and a black version.

WiPi® in short (I registered it, so do not even try).

Fully featured flying devices and very easily modified.

With an ESP and battery (safely) strapped to their backs.

They have got a little LED helmet, indicating mesh activity.

The white version was designed for the warmer climates.

This one keeps really cool; deflecting heat from the sun.

Or you can get the black version for the colder climates.

This one really performs well in sub-zero temperatures.

Obviously it overheats quickly when temperatures rise.

For internet access you can deploy an additional Eagle.

Carrying a tiny satellite modem and wireless antenna.

The Eagle also keeps the pigeons flying in formation. 

If they try to leave it is dinner time for Mr. Eagle.

You can use WiPi® for instant networks,  etc.

I am working on the animal rights issues.

If you want to know more…. maybe.

You would have to sign an NDA.

Yes I know, it is really cool.

WiPi®; anytime, anywhere!

The power saving option is for;

ECO WiPi®! it uses tiny solar panels.

They can stay airborne for about a day.

Power foods are available for both versions.

This keep them airborne for a little longer.

They also feature self-destruct options.

For the more sensitive applications.

Obviously this is not for everyone.

There are export restrictions and such.

They fully vaporize, so do not worry.

Let me know if you are interested.
