### ISSUE TITLE
PainlessMesh is not working as a mesh!

### ISSUE THREAD

**Issue by iVisionary** [gmag11/painlessMesh#8]
Dears, I'm trying to send a short message from one node to all nodes in the mesh. When all nodes are close to the intended AP which sends the broadcast message, everything works fine since all nodes are connected directly to the AP "the sender". Then I took 2 nodes away from the AP, one with external antenna to be able to connect directly to the AP, and the other node without external antenna. The one without ext. antenna couldn't connect to the AP directly and supposed to connect to the nearby one which's got antenna. But that didn't happened! The node without antenna stayed disconnected all the time. 

Broadcast Node intended AP code:-
```Arduino
#include <painlessMesh.h>
#include <ESP8266WiFi.h>
painlessMesh mesh;
int indPin = 2;
void setup() {
  Serial.begin(115200);
  Serial.println();
  pinMode(indPin, OUTPUT);
  digitalWrite(indPin, 1);
  mesh.init(ssid, pass, port, STA_AP, AUTH_WPA2_PSK, 1, PHY_MODE_11B, 82, 1, 8);
  mesh.onReceive(&receivedCallback);
}
void loop() {
  mesh.update();
  String msg = "HELLO MESH!";
  mesh.sendBroadcast(msg);
    digitalWrite(indPin, 0);
    delay(5);
    digitalWrite(indPin, 1);
    delay(100);
}
void receivedCallback(uint32_t from, String &msg) {
  Serial.print(millis() / 1000);
  Serial.printf(" : RECEIVED FROM: %u CONTENT: %s \n", from, msg.c_str());
}

Other Nodes Code:- 

#include <painlessMesh.h>
#include <ESP8266WiFi.h>
painlessMesh mesh;
int indPin = 2;
void setup() {
  Serial.begin(115200);
  Serial.println();
  pinMode(indPin, OUTPUT);
  digitalWrite(indPin, 1);
  mesh.init(ssid, pass, port, STA_AP, AUTH_WPA2_PSK, 1, PHY_MODE_11B, 82, 1, 8);
  mesh.onReceive(&receivedCallback);
}
void loop(){
  mesh.update();
}
void receivedCallback(uint32_t from, String &msg) {
  Serial.print(millis() / 1000);
  Serial.printf(" : RECEIVED FROM: %u CONTENT: %s ", from, msg.c_str());
digitalWrite(indPin, 0);
  delay(5);
  digitalWrite(indPin, 1);
  delay(80);
}
```
Is there something missed here?

**Comment by gmag11** [comment]
Please, this is a mirror repository of original one on [GitLab](https://gitlab.com/BlackEdder/painlessMesh).

I've been disconnected from this project for some time and don't know current status. Please, open an issue there so that current developers can help you.
